language:
  - node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm install --dev coveralls
script:
  - jest test --coverage
after_success:
  -npm run coveralls
