export const userConstants = {
	REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
	REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
	REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
	LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
	LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
	LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
	LOGOUT_USER: "USERS_LOGOUT",
};

export const booksConstants = {
	BOOKS_REQUEST: "GET_BOOKS_REQUEST",
	BOOKS_SUCCESS: "GET_BOOKS_SUCCESS",
	BOOKS_FAILURE: "GET_BOOKS_FAILURE",
	ADD_BOOK_REQUEST: "ADD_BOOK_REQUEST",
	ADD_BOOK_SUCCESS: "ADD_BOOK_SUCCESS",
	ADD_BOOK_FAILURE: "ADD_BOOK_FAILURE",
};
