export const userConstants = {
	REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
	REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
	REGISTER_FAILURE: "USERS_REGISTER_FAILURE",
	LOGIN_REQUEST: "USERS_LOGIN_REQUEST",
	LOGIN_SUCCESS: "USERS_LOGIN_SUCCESS",
	LOGIN_FAILURE: "USERS_LOGIN_FAILURE",
	LOGOUT_USER: "USERS_LOGOUT",
};

export const booksConstants = {
	BOOKS_REQUEST: "GET_BOOKS_REQUEST",
	BOOKS_SUCCESS: "GET_BOOKS_SUCCESS",
	BOOKS_FAILURE: "GET_BOOKS_FAILURE",
	ADD_BOOK_REQUEST: "ADD_BOOK_REQUEST",
	ADD_BOOK_SUCCESS: "ADD_BOOK_SUCCESS",
	ADD_BOOK_FAILURE: "ADD_BOOK_FAILURE",
	SINGLE_BOOK_REQUEST: "SINGLE_BOOK_REQUEST",
	SINGLE_BOOK_SUCCESS: "SINGLE_BOOK_SUCCESS",
	SINGLE_BOOK_FAILURE: "SINGLE_BOOK_FAILURE",
	DELETE_BOOK_REQUEST: "DELETE_BOOK_REQUEST",
	DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
	DELETE_BOOK_FAILURE: "DELETE_BOOK_FAILURE",
	EDIT_BOOK_REQUEST: "EDIT_BOOK_REQUEST",
	EDIT_BOOK_SUCCESS: "EDIT_BOOK_SUCCESS",
	EDIT_BOOK_FAILURE: "EDIT_BOOK_FAILURE"
};
